version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Upgrading pip...
      - docker run -v $(pwd):/app -w /app python:3.8 pip install --upgrade pip
      - echo Installing dependencies...
      - docker run -v $(pwd):/app -w /app python:3.8 pip install -r requirements.txt
      - docker run -v $(pwd):/app -w /app python:3.8 pip install pytest
      - docker run -v $(pwd):/app -w /app python:3.8 pip install jinja2 --upgrade
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Flask app...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests...
      - docker run -v $(pwd):/app -w /app python:3.8 pytest