version: 0.2

phases:
  pre_build:
    commands:
      - echo Building Docker image...
      - docker build -t my-python-app .
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Flask app...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests...
      - docker run -v $(pwd):/app -w /app my-python-app pytest