version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Upgrading pip...
      - pip install --upgrade pip
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install pytest
      - pip install jinja2 --upgrade
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Flask app...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests...
      - pytest